name: "Manual"

run-name: "Manual - ${{ github.ref_name }}"
on:
  workflow_dispatch:
    inputs:
      pipeline:
        description: 'Target Pipeline for Deployment'
        required: true
        type: choice
        options:
          - Test

permissions:
  contents: read

jobs:
  export-envs:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

